services:
  nginx_proxy_manager_service:
    container_name: nginx_proxy_manager_service
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '8080:80'
      - '8081:81'
      - '8443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
