services:
  pihole_service:
    container_name: pihole_service
    image: pihole/pihole:latest
    ports:
      - '7053:53/tcp'
      - '7053:53/udp'
      - '7080:80/tcp'
    environment:
      TZ: 'Eire'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
